export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEMS_BY_ID = "GET_ITEMS_BY_ID";
export const CREATE_ITEM = "CREATE_ITEM";
export const CREATE_MANY_ITEMS = "CREATE_MANY_ITEMS";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const UPDATE_ITEM_QUANTITY = "UPDATE_ITEM_QUANTITY";
export const SUBTRACT_ITEM_QUANTITY = "SUBTRACT_ITEM_QUANTITY";
export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_MANY_ITEMS = "DELETE_MANY_ITEMS";

export const LOADING_ITEMS = "LOADING_ITEMS";
export const END_LOADING_ITEMS = "END_LOADING_ITEMS";
export const LOADING_ITEM = "LOADING_ITEM";
export const END_LOADING_ITEM = "END_LOADING_ITEM";
export const LOADING_ITEM_QUANTITY = "LOADING_ITEM_QUANTITY";
export const END_LOADING_ITEM_QUANTITY = "END_LOADING_ITEM_QUANTITY";
