export const products_example = [
  {
    name: "Hambúrguer Clássico",
    description:
      "Um suculento hambúrguer feito com carne Angus, alface, tomate e molho especial, servido no pão de brioche.",
    price: 15.5,
    quantity: 50,
    created_at: "2023-08-24 10:00:00",
    barcode: "123456789",
    image: "hamburguer_classico.jpg",
    category: "Sanduíches",
    tags: ["hambúrguer", "sanduíche", "carne"],
  },
  {
    name: "Salada Caesar",
    description: "Uma salada fresca com alface, frango grelhado, croutons e molho Caesar cremoso.",
    price: 12.75,
    quantity: 30,
    created_at: "2023-08-24 11:30:00",
    barcode: "987654321",
    image: "salada_caesar.jpg",
    category: "Saladas",
    tags: ["salada", "frango", "leve"],
  },
  {
    name: "Massa Carbonara",
    description: "Uma massa deliciosa com molho carbonara rico e bacon crocante.",
    price: 18.25,
    quantity: 25,
    created_at: "2023-08-24 13:15:00",
    barcode: "567891234",
    image: "massa_carbonara.jpg",
    category: "Massas",
    tags: ["massa", "carbonara", "bacon"],
  },
  {
    name: "Pizza Margherita",
    description: "Uma pizza clássica com molho de tomate, queijo mussarela e folhas frescas de manjericão.",
    price: 20.0,
    quantity: 40,
    created_at: "2023-08-24 14:45:00",
    barcode: "345678912",
    image: "pizza_margherita.jpg",
    category: "Pizzas",
    tags: ["pizza", "margherita", "queijo"],
  },
  {
    name: "Sopa do Dia",
    description: "Uma sopa caseira reconfortante, feita com os ingredientes mais frescos do dia.",
    price: 8.5,
    quantity: 20,
    created_at: "2023-08-24 16:00:00",
    barcode: "789123456",
    image: "sopa_dia.jpg",
    category: "Sopas",
    tags: ["sopa", "caseira", "conforto"],
  },
  {
    name: "Taco de Peixe",
    description: "Taco de peixe grelhado com coentro, cebola roxa e molho de abacate, servido em tortilhas de milho.",
    price: 14.0,
    quantity: 35,
    created_at: "2023-08-24 17:30:00",
    barcode: "234567891",
    image: "taco_peixe.jpg",
    category: "Tacos",
    tags: ["taco", "peixe", "tortilha"],
  },
  {
    name: "Frango Assado",
    description: "Frango suculento assado lentamente com ervas aromáticas, acompanhado de legumes frescos.",
    price: 16.75,
    quantity: 15,
    created_at: "2023-08-24 19:00:00",
    barcode: "456789123",
    image: "frango_assado.jpg",
    category: "Pratos Principais",
    tags: ["frango", "assado", "legumes"],
  },
  {
    name: "Bruschetta",
    description: "Fatias de pão italiano torrado com tomate, manjericão, alho e azeite de oliva.",
    price: 9.25,
    quantity: 40,
    created_at: "2023-08-24 20:15:00",
    barcode: "891234567",
    image: "bruschetta.jpg",
    category: "Entradas",
    tags: ["bruschetta", "pão italiano", "antepasto"],
  },
  {
    name: "Smoothie de Frutas",
    description: "Um smoothie refrescante feito com uma mistura de frutas tropicais e iogurte.",
    price: 7.5,
    quantity: 25,
    created_at: "2023-08-24 22:00:00",
    barcode: "234567890",
    image: "smoothie_frutas.jpg",
    category: "Bebidas",
    tags: ["smoothie", "frutas", "iogurte"],
  },
  {
    name: "Tiramisù",
    description:
      "Uma sobremesa clássica italiana com camadas de biscoitos de champanhe embebidos em café e creme de mascarpone.",
    price: 10.5,
    quantity: 20,
    created_at: "2023-08-24 23:30:00",
    barcode: "678901234",
    image: "tiramisu.jpg",
    category: "Sobremesas",
    tags: ["tiramisù", "doce", "café"],
  },
  {
    name: "Café Expresso",
    description: "Um café expresso curto e encorpado, perfeito para uma dose de energia.",
    price: 3.0,
    quantity: 50,
    created_at: "2023-08-25 08:00:00",
    barcode: "345678901",
    image: "cafe_espresso.jpg",
    category: "Bebidas",
    tags: ["café", "expresso", "energia"],
  },
  {
    name: "Bolo do Dia",
    description: "Um bolo fresco e delicioso, preparado diariamente com os melhores ingredientes disponíveis.",
    price: 5.75,
    quantity: 15,
    created_at: "2023-08-25 10:30:00",
    barcode: "456789012",
    image: "bolo_dia.jpg",
    category: "Sobremesas",
    tags: ["bolo", "fresco", "doce"],
  },
];
